### ISSUE TITLE
Expiry time

### ISSUE THREAD

**Issue by caspadan** [Rookiestyle/PEDCalc#5]
## Summary
I have some passwords that if you do not change the password before expiration, your account gets suspended / you need to have your password reset (not a simple self-reset).

So, for example, you set a password to expire in 90 days - the 90th day then being the (last) day to reset your password as the next day it will be expired and your account suspended.   PEDCalc sets the time for the password to expire at 23:59:59 - which makes perfect sense and is exactly correct. However, this means when the password shows as expired in KeePass, it is too late.

It could maybe work to add an optional value next to the expiry days value. Like a checkbox that, if checked, a time of day can be specified (and if unchecked, default PEDCalc time). Obviously I've put minimal thought into the implementation, but just an example.

## Added value
The value added would be for instances described above, where the expiration of the password equals the suspension of the account.

## Example
This is just an example
![Untitled](https://github.com/Rookiestyle/PEDCalc/assets/61324156/444507cc-1f3a-480c-a602-3ee6ecdaea61)

## Conclusion
It's just a suggestion, so it really depends on how you feel.  Either way, it doesn't matter.

On another note, I'm not going to post a whole bug report (unless it is one and you would like me to), but I notice the PEDCalc calculation under the expiry date field on the edit entry dialog only shows up when i focus (click) outside of KeePass and then focus back on KeePass.

**Comment by Rookiestyle** [comment]
I close this one as the alerting you ask for is already covered by [KPColorChange](https://github.com/Rookiestyle/KPColorChange) 


> On another note, I'm not going to post a whole bug report (unless it is one and you would like me to), but I notice the PEDCalc calculation under the expiry date field on the edit entry dialog only shows up when i focus (click) outside of KeePass and then focus back on KeePass.

Please post a bug report and include as much details as possible
Expected behaviour: PEDCalc calculation is shown if
* PEDCalc is active for this entry 
* and the entry can expire (Expires checkbox is active) 
* and the expiry date was not changed manually
* and the password was changed

**Comment by caspadan** [comment]
Awesome, wasn't aware of that plugin.. Damn, all your plugins are super useful.  Thank you.

What a noob I am.. I just looked at your points and opened the edit entry and as soon as I changed the password, the calculation appeared, so I just wasn't aware how the plugin behaved.  Thank you.
